# Generated by Django 6.0.4 on 2026-04-22 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={
                "ordering": ["-is_pinned", "-updated_at"],
                "verbose_name": "会话",
                "verbose_name_plural": "会话",
            },
        ),
        migrations.AlterModelOptions(
            name="conversationfolder",
            options={
                "ordering": ["sort_order", "-created_at"],
                "verbose_name": "会话文件夹",
                "verbose_name_plural": "会话文件夹",
            },
        ),
        migrations.AddField(
            model_name="conversation",
            name="agent_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Agent 标识"
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="is_pinned",
            field=models.BooleanField(default=False, verbose_name="置顶"),
        ),
        migrations.AddField(
            model_name="conversationfolder",
            name="sort_order",
            field=models.IntegerField(default=0, verbose_name="排序权重"),
        ),
        migrations.AddField(
            model_name="message",
            name="tokens_used",
            field=models.IntegerField(default=0, verbose_name="Token 消耗"),
        ),
        migrations.AddField(
            model_name="message",
            name="workflow_id",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="LangGraph 执行 ID"
            ),
        ),
        migrations.AddField(
            model_name="promptlibrary",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="message",
            name="metadata_json",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="存放 Agent 完整执行轨迹（entries 数组），用于前端还原思考步骤",
                verbose_name="Agent 执行轨迹",
            ),
        ),
        migrations.CreateModel(
            name="MessageAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=500, verbose_name="原始文件名"),
                ),
                (
                    "file_path_minio",
                    models.CharField(max_length=500, verbose_name="MinIO 存储路径"),
                ),
                ("file_size", models.IntegerField(default=0, verbose_name="文件大小")),
                (
                    "content_type",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="MIME 类型"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="chat.message",
                        verbose_name="消息",
                    ),
                ),
            ],
            options={
                "verbose_name": "消息附件",
                "verbose_name_plural": "消息附件",
            },
        ),
    ]
