# Generated by Django 6.0.4 on 2026-04-28 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_alter_conversation_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_name",
                    models.CharField(
                        default="default", max_length=100, verbose_name="Agent 标识"
                    ),
                ),
                ("fact", models.TextField(verbose_name="事实内容")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("preference", "偏好"),
                            ("knowledge", "知识"),
                            ("goal", "目标"),
                            ("context", "背景"),
                        ],
                        max_length=50,
                        verbose_name="分类",
                    ),
                ),
                ("confidence", models.FloatField(default=0.5, verbose_name="置信度")),
                (
                    "source_conv_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="来源会话 ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "access_count",
                    models.IntegerField(default=0, verbose_name="被使用次数"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户记忆",
                "verbose_name_plural": "用户记忆",
                "db_table": "chat_memory",
                "indexes": [
                    models.Index(
                        fields=["user", "agent_name", "-confidence"],
                        name="idx_memory_user_conf",
                    ),
                    models.Index(
                        fields=["user", "category"], name="idx_memory_user_cat"
                    ),
                ],
            },
        ),
    ]
