# Generated by Django 6.0.4 on 2026-04-30 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_add_user_memory"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="feedback_detail",
            field=models.JSONField(
                blank=True,
                help_text='{"reasons": ["内容准确"], "comment": "可选文本"}',
                null=True,
                verbose_name="反馈详情",
            ),
        ),
    ]
