# Generated by Django 6.0.4 on 2026-04-30 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_message_feedback_detail"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=500, verbose_name="文件名")),
                (
                    "minio_path",
                    models.CharField(max_length=500, verbose_name="MinIO 路径"),
                ),
                (
                    "file_size",
                    models.IntegerField(default=0, verbose_name="文件大小(bytes)"),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pptx", "PowerPoint"),
                            ("pdf", "PDF"),
                            ("xlsx", "Excel"),
                            ("other", "其他"),
                        ],
                        default="pptx",
                        max_length=20,
                        verbose_name="文件类型",
                    ),
                ),
                (
                    "slide_count",
                    models.IntegerField(default=0, verbose_name="幻灯片页数"),
                ),
                (
                    "theme",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="主题风格"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="为空表示不过期",
                        null=True,
                        verbose_name="过期时间",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_files",
                        to="chat.conversation",
                        verbose_name="关联会话",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_files",
                        to="chat.message",
                        verbose_name="关联消息",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 生成文件",
                "verbose_name_plural": "AI 生成文件",
                "db_table": "chat_generated_file",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="idx_genfile_user_created"
                    )
                ],
            },
        ),
    ]
