# Generated by Django 6.0.4 on 2026-04-21 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="文档 ID"
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=500, verbose_name="原始文件名"),
                ),
                (
                    "minio_path",
                    models.CharField(max_length=500, verbose_name="MinIO 路径"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, verbose_name="文件大小(字节)"
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="MIME 类型"
                    ),
                ),
                (
                    "department",
                    models.CharField(blank=True, max_length=100, verbose_name="部门"),
                ),
                (
                    "category_l1",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="一级分类"
                    ),
                ),
                (
                    "category_l2",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="二级分类"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "处理失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Celery 任务 ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "kb",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="users.knowledgebase",
                        verbose_name="所属知识库",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传者",
                    ),
                ),
            ],
            options={
                "verbose_name": "文档",
                "verbose_name_plural": "文档",
                "ordering": ["-created_at"],
            },
        ),
    ]
