# Generated by Django 6.0.4 on 2026-04-21 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0002_remove_document_department_document_is_active_and_more"),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="category_l1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents_l1",
                to="tags.tag",
                verbose_name="一级分类",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="category_l2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents_l2",
                to="tags.tag",
                verbose_name="二级分类",
            ),
        ),
    ]
