# Generated by Django 6.0.4 on 2026-04-21 16:25

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def populate_phone(apps, schema_editor):
    """为现有用户设置唯一手机号"""
    User = apps.get_model("users", "User")
    for user in User.objects.all().order_by("id"):
        user.phone = "1000000%04d" % user.id
        user.save(update_fields=["phone"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_active_by_admin",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_knowledge_bases",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="激活状态"),
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        # 先加 phone 列（非 unique，有默认空值）
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                default="", max_length=20, verbose_name="手机号"
            ),
        ),
        # 为现有用户填充唯一手机号
        migrations.RunPython(populate_phone, migrations.RunPython.noop),
        # 现在所有 phone 值唯一，加 unique 约束
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                default="", max_length=20, unique=True, verbose_name="手机号"
            ),
        ),
        migrations.AddField(
            model_name="userkbpermission",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="授权时间"
            ),
        ),
        migrations.AddField(
            model_name="userkbpermission",
            name="granted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="granted_kb_permissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="授权人",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="注册时间"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, default="", max_length=254, verbose_name="邮箱"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="激活状态"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="staff status"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="用户名",
            ),
        ),
    ]
