# Generated by Django 6.0.4 on 2026-04-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers_remove_user_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=20, unique=True, verbose_name="手机号"),
        ),
        migrations.AlterField(
            model_name="userkbpermission",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="授权时间"),
        ),
    ]
