# Generated by Django 6.0.4 on 2026-04-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_phone_alter_userkbpermission_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="头像"
            ),
        ),
    ]
