# Generated by Django 6.0.4 on 2026-04-22 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_avatar_charfield"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
    ]
